fotoley/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('social.urls')),
    path('admin/', admin.site.urls)
]

social/urls.py
from django.urls import path
from .views import *

app_name = "social"
urlpatterns = [
    path("login", Login.as_view(), name="login"),
    path("register", Register.as_view(), name="register"),
    path("", Home.as_view(), name="home"),
    path("logout", Logout.as_view(), name="logout"),
]

social/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

class  CustomAccountManager(BaseUserManager):
    def create_user(self, email, username,  password, first_name, last_name, **other_fields):
    
        if not email:
            raise ValueError("Users must have email address")
        if not username:
            raise ValueError("Users must have an username")    
        if not first_name:
            raise ValueError("Users must have a first_name")
        if not last_name:
            raise ValueError("Users must have a last_name")
        
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, first_name=first_name, last_name=last_name)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self, email, username, password, first_name, last_name, **other_fields):
        
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError('Superuser has to be assigned is_staff = True')
        
        if other_fields.get('is_superuser') is  not True:
            raise ValueError('Superuser has to be assigned is_superuser = True')

        return self.create_user(email, username, password, first_name, last_name, **other_fields)

class User(AbstractUser):
    email = models.EmailField(unique=True, null=False, blank=False)
    password = models.CharField(max_length=250)
    
    first_name = models.CharField(max_length=100,null=False, blank=False)
    last_name = models.CharField(max_length=100,null=False, blank=False)
    following = models.ManyToManyField("social.User", blank=True, related_name="followed_by")
    followers = models.ManyToManyField("social.User", blank=True, related_name="follows")
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']
    objects = CustomAccountManager()

    def __str__(self):
        return self.username

social/views.py
from curses import use_default_colors
from django.views import View
from django.contrib.auth import get_user_model, authenticate
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import *

class Login(View):
    def get(self, request):
        if 'user_id' in request.session:
            return HttpResponseRedirect('')
        
        return render(request, 'social/login.html', {
        })

    def post(self, request, *args, **kwargs):
        email = request.POST['email']
        password = request.POST['password']
        
        user = authenticate(email=email, password=password)
        if user is not None:
            request.session['user_id'] = user.id
            return HttpResponseRedirect('/')
        else:
            return HttpResponseRedirect('login')

class Register(View):
    def post(self, request, *args, **kwargs):
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        username = email.split('@')[0]
        print(first_name, last_name)
        get_user_model().objects.create_user(email, username, password, first_name, last_name)
        
        return HttpResponseRedirect('login')	

class Home(View):
    def get(self, request):
        # Get all users list except self , render it
        # Get all the post of followed users

        user_id = request.session['user_id']
        users = User.objects.exclude(id=user_id).exclude(username='admin')
        print(users)
        return render(request, 'social/index.html', {
        })

class Logout(View):
    def get(self, request):
        try:
            del request.session['user_id']
            return HttpResponseRedirect('login')
        except KeyError as e:
            print(e)
            return HttpResponseRedirect('/')

social/templates/social/index.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Hello, world!</title>
  </head>
  <body>

    <div class="d-flex bd-highlight m-5">
      <div class="flex-fill bd-highlight card border-dark m-3 p-2">
        <div class="card">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Shaikh Mudassir <button type="button" class="btn btn-outline-primary float-end">Follow</button></li>
          </ul>
        </div>
      </div>


      <div class="flex-fill bd-highlight card border-dark m-3 p-2">
        <img src="{% static 'social/1.png' %}" class="card-img-top w-50 p-3" alt="...">
        <div class="card-body">
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>


      <div class="flex-fill bd-highlight m-3 p-2">
        <a href="{% url 'social:logout' %}"><button type="button" class="btn btn-success" style="width: 100%;">Logout</button></a>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

social/templates/social/login.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'social/style.css' %}">
  </head>
  <body>
    <div class="d-flex justify-content-center align-items-center mt-5">
      <div class="card">
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item text-center">
              <a class="nav-link active btl" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Login</a>
            </li>
            <li class="nav-item text-center">
              <a class="nav-link btr" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Signup</a>
            </li>
        </ul>
        <div class="tab-content" id="pills-tabContent">
          <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
            <form action="{% url 'social:login' %}" method="POST" class="form px-4 pt-5">
              {% csrf_token %}
              <input type="email" name="email" class="form-control" placeholder="Email">
              <input type="password" name="password" class="form-control" placeholder="Password">
              <button class="btn btn-dark btn-block">Login</button>
            </form>
          </div>
          <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
            <form action="{% url 'social:register' %}" method="POST" class="form px-4">
              {% csrf_token %}
              <input type="text" name="first_name" class="form-control" placeholder="First Name">
              <input type="text" name="last_name" class="form-control" placeholder="Last Name">
              <input type="email" name="email" class="form-control" placeholder="Email">
              <input type="password" name="password" class="form-control" placeholder="Password">
              <input type="password" name="c_password" class="form-control" placeholder="Confirm Password">
              <button class="btn btn-dark btn-block">Signup</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</html>